imports:
    - { resource: resources.yaml }
    - { resource: sylius_ui.yaml }
    - { resource: grids.yaml }


knp_gaufrette:
    stream_wrapper: ~
    adapters:
        store_logo:
            local:
                directory: "%sylius_core.public_dir%/media/store-logo"
                create: true
    filesystems:
        store_logo:
            adapter: store_logo

liip_imagine:
    loaders:
        store_logo:
            filesystem:
                data_root: "%kernel.project_dir%/public/media/store-logo"
    filter_sets:
        dotit_sylius_store_plugin_logo:
            data_loader: store_logo
            filters:
                thumbnail: { size: [300, 300], mode: outbound }
